# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "designmakerapp"
client_id = "1c5c035607424ad3ff175e29d947282c"
application_url = "https://leaving-peripherals-ment-minority.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_script_tags,write_script_tags,write_files,read_files,write_themes "

[auth]
redirect_urls = [
  "https://leaving-peripherals-ment-minority.trycloudflare.com/auth/callback",
  "https://leaving-peripherals-ment-minority.trycloudflare.com/auth/shopify/callback",
  "https://leaving-peripherals-ment-minority.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ds-desingmaker.myshopify.com"
