# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "designmakerapp"
client_id = "573b48162a6f2150198d618978eebc41"
application_url = "https://shopify-cli-app-2ff8c09347c3.herokuapp.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_script_tags,write_script_tags,write_files,read_files"

[auth]
redirect_urls = [ "https://shopify-cli-app-2ff8c09347c3.herokuapp.com/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "ds-desingmaker.myshopify.com"
